### ISSUE TITLE
We should support custom unary operators

### ISSUE THREAD

**Issue by VinGarcia** [cparse/cparse#40]
Currently we allow our users to define custom binary operators, but not unary.

Since this is a very basic concept we should handle this sometime soon.

**Comment by zhxilin** [comment]
Yes, custom unary operator support is necessary. In my case, I would like to add reverse operator, here is a workaround by now:
```
OppMap_t& opp = calculator::Default().opPrecedence;
opp.add("!", 4); // between ** and *
opMap_t& opMap = calculator::Default().opMap;
opMap.add({ BOOL, "!", BOOL }, &Reverse);
```

```
packToken Reverse(const packToken& left, const packToken& right, evaluationData* data)
{
       //ignore the left operand
	return !right.asBool();
}
```

And, add the following code to rpnBuilder::handle_unary:
```
...
else if (!op.compare("!"))
{
        this->rpn.push(new Token<bool>(true, BOOL));
        return this->lastTokenWasUnary = true;
}
```

**Comment by VinGarcia** [comment]
Yes, that is important, thanks for sharing your solution =].

I was giving my priority to the new Mark & Sweep Garbage collector but I can probably add this new feature quickly. I will try doing that this weekend. I'll report back when I get it working.

**Comment by VinGarcia** [comment]
Finished adding support for unary operators: 2b4fa5f3b3b24cfb00d5d4d9b9071ec0b57b15b9

Now it is possible to add your own left-unary operators and it is only a little different from adding a binary operator:

```C++
// Add it to the opPrecedence struct:
opp.addUnary("+",  3); opp.addUnary("-", 3);

// And add a function for handling the operations:
opMap.add({UNARY, ANY_OP, NUM}, &UnaryNumeralOperation);
```

The `UnaryNumeralOperation` is just like any function you would create for a binary operation, the
difference is that the left operand is useless and contains a token of type `UNARY`.

I tested it should be working.

Also some notes:
- By adding the new `UNARY` type, it might collide with previously created user-defined types, so watchout for that.
- A previous commit changed the name of `objects.h` to `containers.h` if you were including this file in your code you'll have to update it.

Let me know if everything is working on your environment.

**Comment by zhxilin** [comment]
It works perfect! Thx!

**Comment by VinGarcia** [comment]
That's great =], I'll close the issue when I add support for right-side unary operators as well.

**Comment by VinGarcia** [comment]
Just added support for right unary operators: c8a79020f9874e3177fe21425abb810e7376b5d8

This commit also fixes a bug with the left unary operators so @zhxilin you should probably pull these changes.

The only thing that is not so cool about this commit is that it is not yet possible to accept "lvalues" in
the operations, thus: `a++` and `a--` is not implementable yet, even though it is possible to
make an operator "not" to work on the right side, e.g. `a!` or `a~`.

I will close this issue and open a new one for adding access for lvalues inside the operations.

**Comment by VinGarcia** [comment]
Also, @zhxilin since this is a new feature there might be some new bugs I haven't detected with my tests if you find any you may report on this same issue or create a new one.

**Comment by zhxilin** [comment]
Great! Thank you!
