### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by KrzysztofSakowski** [cparse/cparse#47]
Link in "As a sub-parser for a programming language." section of README.md file to "jSpy programming language" raises 404 error.

**Comment by VinGarcia** [comment]
Thank you @KrzysztofSakowski, just fixed it in 5f2633abe8004104e294d423f5849aed6e940ff9.

If you plan to checkout the JSpy project now, I suggest you to checkout the `dissertation` branch (the current most stable).
