### ISSUE TITLE
handle_unary() not working?

### ISSUE THREAD

**Issue by chan-tw** [cparse/cparse#48]
Hi,

The following unary expressions break:
```
Expr '3 * -4' -> -4
Expr '3 / -4' -> inf
Expr '3 - -4' -> -1
Expr '3 + -4' -> -1
```

Code used is very basic:
```
#include <iostream>
#include "shunting-yard.h"

int main(int argc, char* argv[])
{
    TokenMap vars;
    vars["pi"] = 3.14;

    std::string str;
    for (int idx = 1; idx < argc; ++idx) {
        if (idx > 1)
            str += ' ';
        str += argv[idx];
    }
    std::cout << "Expr: '" << str << "'\n";
    std::cout << calculator::calculate(str.c_str(), &vars) << std::endl;
    return 0;
}
```

It seems `rpnBuilder::handle_unary()` is not creating the correct RPN output for the above cases; debugged RPN output of the above show:
```
compile: '3 * -4'
    RPN: TokenINT(3) TokenINT(0) TokenOP(*) TokenINT(4) TokenOP(-)

compile: '3 / -4'
    RPN: TokenINT(3) TokenINT(0) TokenOP(/) TokenINT(4) TokenOP(-)

compile: '3 + -4'
    RPN: TokenINT(3) TokenINT(0) TokenOP(+) TokenINT(4) TokenOP(-)

compile: '3 - -4'
    RPN: TokenINT(3) TokenINT(0) TokenOP(-) TokenINT(4) TokenOP(-)
```

**Comment by VinGarcia** [comment]
Uhm, that is true! It was easy to reproduce, I wonder how it wasn't detected before. I will work on it.

Thanks!

**Comment by VinGarcia** [comment]
Fixed @chan-tw, it seems I added this bug not long ago and there was not test to prevent me from doing it. I added a new test and fixed the bug.

Also, sorry for the delay for reading your post, either github did not bother to sent me an e-mail or gmail blocked it.

**Comment by chan-tw** [comment]
@VinGarcia Thanks, good fix.
