### ISSUE TITLE
Operators from alphabetic characters

### ISSUE THREAD

**Issue by astlin** [cparse/cparse#50]
Is it possible to create operators from alphabetic characters i.e. "and", "or", "like"?

**Comment by VinGarcia** [comment]
Yes it is we have the reserved words concept.

On the JSpy programming language for example I have implemented operator 'in' `if (10 in [1,2,3,4,5]) { ... }.

Sorry for the delay to answer I can't get gmail to properly highlight these e-mails for me.

**Comment by VinGarcia** [comment]
Reoppening this issue.

I'll close it after I write the some documentation on the wiki explaining how to do this.

**Comment by VinGarcia** [comment]
I have added an explanation on how to do this on a new Wiki page: [Reserved Word Operators](https://github.com/cparse/cparse/wiki/Reserved-Word-Operators)

If you think the explaining is good enough you may close the issue, or else tell me what are you doubts and I'll try to improve the text.
