### ISSUE TITLE
Link operations to operators problem.

### ISSUE THREAD

**Issue by astlin** [cparse/cparse#54]
I've defined non-strict comparison operator '=%':

`opp.add("==", 9); opp.add("!=", 9); opp.add("=%", 9);`

But it won't match 'ANY_OP' pattern, so this do not work:

`opMap.add({ARR, ANY_OP, ANY_TYPE}, &ArrayOnAnyOperation);`

And I have to define it explicitly:

```
opMap.add({ARR, ANY_OP, ANY_TYPE}, &ArrayOnAnyOperation);
opMap.add({ARR, "=%", ANY_TYPE}, &ArrayOnAnyOperation);

```

**Comment by VinGarcia** [comment]
The masking system is a little complicated. I can think of 2 possible reasons for this problem:

1. ARR ID is colliding with some existing type making the operation be processed by some built-in one instead of the one you were expecting.
2. You have defined a more specific operation for this same types, e.g. `opMap.add({ANY_TYPE, "=%", ANY_TYPE})`

Can you provide the code you use to declare all your operations as well as the hex numeral of `ARR`? Then I should be able to diagnose what is happening.

**Comment by astlin** [comment]
Well, actually there is a declaration of '=%' for ANY_TYPE on ANY_TYPE right before the last one 'ANY ANY ANY'. 

```
opMap.add({ARR, ANY_OP, ANY_TYPE}, &ArrayOnAnyOperation);
opMap.add({ARR, "=%", ANY_TYPE}, &ArrayOnAnyOperation);
....
opMap.add({ANY_TYPE, "=%", ANY_TYPE}, &AnyLike);
opMap.add({ANY_TYPE, ANY_OP, ANY_TYPE}, &AnyOnAny);

```

**Comment by VinGarcia** [comment]
This `{ANY, =%, ANY}` operation is most likely taking precedence.

The `ANY_OP` operations are only evaluated if there is no match with a specific operation, quoting the code:

```C++
// Resolve the operation: 
result = exec_operation(p_left, p_right, &data, data.op); 
if (!result) {
  // ANY_OP will only run if no other match is found:
  result = exec_operation(p_left, p_right, &data, ANY_OP); 
}
```

This could probably be better explained in the docs. In any case I suggest you group your `ANY_OP` operation declarations and set put them after the rest, so it will be more clear the actual precedence order:

```C++
// The order is important between 2 operations with the same operator
// So ARR "=%" ANY will have precedence over ANY "=%" ANY
opMap.add({ARR, "=%", ANY_TYPE}, &ArrayOnAnyOperation);
opMap.add({ANY_TYPE, "=%", ANY_TYPE}, &AnyLike);

// Likewise {ARR ANY_OP ANY} will have precedence over {ANY ANY_OP ANY}
// But ANY_OP will always have less precedence than specific operations so they should
// be put in last to make it clear.
opMap.add({ARR, ANY_OP, ANY_TYPE}, &ArrayOnAnyOperation);
opMap.add({ANY_TYPE, ANY_OP, ANY_TYPE}, &AnyOnAny);
```

I will add this example to the docs and then, if it works for you, close this issue.

**Comment by VinGarcia** [comment]
I have updated the doc [section on this](https://github.com/cparse/cparse/wiki/Defining-New-Operations#operation-matching-loop), and it should be clearer now.

Let me know if this helps.

**Comment by astlin** [comment]
Ok. Thanx for explanation.
