### ISSUE TITLE
strtol() in calculator::toRPN can't support 64bit integers on MinGW, Windows

### ISSUE THREAD

**Issue by thelxz** [cparse/cparse#62]
Hi, cparse is work pretty well on Linux. But when I compile it by MinGW on Windows, the high 32 bits of numbers is allways 0.
It seems `long int strtol(...)` function return 32-bit integer, rather than 64-bit integer on MinGW/Windows, because of the data model of Windows is LLP.
related code:
``` c
      // If the token is a number, add it to the output queue.
      int64_t _int;
      _int = strtol(expr, &nextChar, 10);
```
Maybe the `strtoll()` is better?

**Comment by VinGarcia** [comment]
Hello @thelxz, sorry for taking so long to answer and thank you for reporting this. This seems like a good idea, I will try to create a MinGW environment and test if this fixes the problem. 

If it doesn't I will look for another solution.

**Comment by VinGarcia** [comment]
Hello @thelxz, I was unable to reproduce the problem on my environment so I can't be sure my last push really fixed the problem. I only replaced `strtol()` for `strtoll()` as you suggested.

Can you confirm if this fixes the problem?

**Comment by thelxz** [comment]
It works! This problem has been fixed.
My fault, I should have provided the failed test case at first. The test code:
```  c++
  TokenMap vars;
  calculator c1("17587891077120+1");  //  0xFFF_0000_0000 + 1
  std::cout << c1.eval(vars) << std::endl; 
```
Output with `strtol()`:
```
2.14748e+009
```
Output with `strtoll()`:
```
1.75879e+013
```

**Comment by VinGarcia** [comment]
That's good! Thanks for the test code, I will add a test for it so this doesn't happen again.
