### ISSUE TITLE
Memory leak due to lack of std::forward

### ISSUE THREAD

**Issue by EpsilonQ** [cparse/cparse#67]
Lack of proper forwarding is causing packToken(const packToken&) to be called instead of packToken(packToken&&), given this, the destructor of the local pass in arguments was also not being c
    valgrind:memcheck 387,960 bytes in 16,165 blocks are definitely lost in loss record 261 of 267
    valgrind:memcheck    at 0x4C2A203: operator new(unsigned long) (vg_replace_malloc.c:334)
    valgrind:memcheck    by 0x1D7FD5A: Token<double>::clone() const (shunting-yard.h:71)
    valgrind:memcheck    by 0x1D67CB9: RefToken::RefToken(packToken, TokenBase*, packToken) (shunting-yard.h:285)

**Comment by VinGarcia** [comment]
Hello @EpsilonQ, thanks for your contribution, let's continue this discussion on PR #68.

**Comment by VinGarcia** [comment]
PR #68 was merged, I am closing this issue. Thanks @EpsilonQ for the contribution.
