### ISSUE TITLE
visual studio 2019 + mfc + cparser

### ISSUE THREAD

**Issue by pandrew83** [cparse/cparse#69]
hi.
In MFC defined type BOOL. But cparser redefines identifier BOOL in shunting-yard.h at line 37.
I don't know what i do now. I can't change MFC BOOL. May be change BOOL in shunting-yard.h?
Do you have solution?

**Comment by VinGarcia** [comment]
The correct solution would probably be to wrap the cparse library on a
namespace.

I will make this change when I get home.

Thanks for reporting this problem!

Em dom, 26 de mai de 2019 12:13, pandrew83 <notifications@github.com>
escreveu:

**Comment by pandrew83** [comment]
hello
When you can close this issue?

**Comment by VinGarcia** [comment]
Oh I forgot about this one, sorry @pandrew83 I will close it now =]
