### ISSUE TITLE
"ld: unknown option: -O1" when compiling on macOS

### ISSUE THREAD

**Issue by ianhinder** [cparse/cparse#70]
When compiling on macOS, I get
```
$ make release -C cparse
...
ld -r -O1 shunting-yard.o packToken.o functions.o containers.o -o core-shunting-yard.o
ld: unknown option: -O1
```
because -O1 is not a valid option to the macOS (BSD) linker.  I've not come across the -O flag at link time before; is it necessary here?  It seems to be gcc-specific.  I'd just drop it for simplicity and portability if it's not really necessary.

This could be defined in LDFLAGS in the Makefile, which would allow the user to override LDFLAGS to either add or remove the -O1 option depending on whether you decided to keep it or not.

**Comment by sandszhouSZ** [comment]
yes, when delete it, the code could compile successfully, but the demo could not run successfully

**Comment by VinGarcia** [comment]
Hello @ianhinder and @sandszhouSZ sorry for the late reply, yes I think we can fix this in the Makefile, about the -O flag at link time, it is indeed a valid argument in Linux:

Running `man ld`:

```
       -O level
           If level is a numeric values greater than zero ld optimizes the output.  This might take significantly longer and therefore probably should only be
           enabled for the final binary.  At the moment this option only affects ELF shared library generation.  Future releases of the linker may make more use
           of this option.  Also currently there is no difference in the linker's behaviour for different non-zero values of this option.  Again this may change
           with future releases.
```

I will create a PR conditioning this `-O1` to Linux , about the `-O3` used with g++, is this one also causing problems on macOS?

**Comment by VinGarcia** [comment]
So I wrote the PR, can you guys test it to see if it is working on your environment, since I don't have a macOS for testing it.

https://github.com/cparse/cparse/pull/87

**Comment by VinGarcia** [comment]
@ianhinder and @sandszhouSZ can you guys help me test the PR #87 ? If it works I can merge it.

**Comment by VinGarcia** [comment]
Since no one answered I will just merge it and if there are any problems I will have to wait for someone that uses Mac to open a ticket.

**Comment by VinGarcia** [comment]
Done.
