### ISSUE TITLE
Example compilation command in README.md doesn't work for me

### ISSUE THREAD

**Issue by ianhinder** [cparse/cparse#71]
If I follow the instructions under Getting Started / Setup, I get an error at the "Link with your project" stage.  This happens on macOS and Linux.  For main.cpp, I am using the example provided later under "Minimal examples".
The first problem is
```
$ g++ cparse/builtin-features.o cparse/core-shunting-yard.o main.cpp -o main
main.cpp:2:27: fatal error: shunting-yard.h: No such file or directory
```
because in the example, compilation happens outside the cparse directory, and cparse is not on the include path.  Adding  -Icparse to the command fixes this of course.

The next error is
```
$ g++ cparse/builtin-features.o cparse/core-shunting-yard.o main.cpp -o main -I cparse
In file included from main.cpp:2:0:
cparse/shunting-yard.h:23:9: error: ‘uint8_t’ does not name a type
 typedef uint8_t tokType_t;
```
This is because uint8_t is a C++11 feature, and this compiler (g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)), does not support C++11 by default.  You need to add -std=c++11.

If I use
```
g++ -std=c++11 cparse/builtin-features.o cparse/core-shunting-yard.o main.cpp -o main -I cparse
```
it compiles fine.  Should the command in the README be updated?

**Comment by VinGarcia** [comment]
Sure, thanks for reporting. I just fixed the README, tell me if you see any problems with the fix.

Since I took forever to answer you might not have the time to look, if that's the case I will close this issue next week.
