### ISSUE TITLE
group/vector operation possible? Naive iteration can be expensive when number of elements is huge

### ISSUE THREAD

**Issue by zxpatric** [cparse/cparse#72]
int main() {
    TokenMap vars;
    vars["pi"] = 3.14;
    std::cout << calculator::calculate("-pi+1", &vars) << std::endl;

    // Or if you want to evaluate an expression
    // several times efficiently:
    calculator c1("pi-b");
    vars["b"] = 0.14;
    std::cout << c1.eval(vars) << std::endl; // 3
    vars["b"] = 2.14;
    std::cout << c1.eval(vars) << std::endl; // 1

    **vars["b"] = {0.1, 0.2};
    std::cout << c1.eval(vars) << std::endl;**

    return 0;
}

**Comment by VinGarcia** [comment]
The current implementation of memory management on lists is not very efficient =/. I belive the best way to fix this would be to implement a special type of list made for only for integers, floats, etc that internally would count as a single std::vector.

We could create a special type such as "TokenIntList" etc, for these cases. However, I currently don't have time to spare =/.

If you want to submit a PR for this it would be welcome, but it might be a little complicated 🤔 .

**Comment by zxpatric** [comment]
Let me see if the naive is acceptable speed wise and how complicated it is to implement TokenIntList.  Is there a way that calculator::calculate can cache the equation interpretation so it doesn't have to parse it every time for every tuple?   For exmaple,   a^2+b*c.  If  there are 3 vectors for a, b, c and each tuple with one element from a, b, c will be called through calculator::calculate("a^2+b*c", &vars). My concern is the parsing time of the equation can be long but can also be saved since it needs to be done only once. Any sight on this?

**Comment by zxpatric** [comment]
Got it. may dig deep into this function and use rpn for naive iteration.

packToken calculator::calculate(const char* expr, TokenMap vars,
                                const char* delim, const char** rest) {
  // Convert to RPN with Dijkstra's Shunting-yard algorithm.
  RAII_TokenQueue_t rpn = calculator::toRPN(expr, vars, delim, rest);

  TokenBase* ret = calculator::calculate(rpn, vars);

  return packToken(resolve_reference(ret));
}

**Comment by VinGarcia** [comment]
About your first comment: If you compile the expression, i.e. create an instance of the calculator class the parsing is made only on the first time. Then for each consecutive call to `eval()` it will only execute the code in the context provided by the TokenMap passed as argument and not parse it.

If this was your concern then I might have misunderstood you.

You can see how to do that on the Getting Started page of the Wiki:

- https://github.com/cparse/cparse/wiki/Getting-Started

The easiest way to do it would be like this:

```C++
TokenMap vars;
calculator C("my_var = x / 4 + 3");

vars["x"] = 8;
std::cout << C.eval(vars) << std::endl; // 5

vars["x"] = 16;
std::cout << C.eval(vars) << std::endl; // 7
```

Is this the issue you needed to fix?, If so you can close this issue.

**Comment by zxpatric** [comment]
Thanks VinGarcia. I did went that way. The speed is o...k for large amount although if there are possibilities to support vectorized operation, the best.
