### ISSUE TITLE
terminating with uncaught exception of type syntax_error: Invalid operator: -

### ISSUE THREAD

**Issue by chrisabrams** [cparse/cparse#74]
Followed the directions fore getting started; compiles fine but when running I'm getting this error:

`terminating with uncaught exception of type syntax_error: Invalid operator: -`

File: `main.cpp`
```c++
#include <iostream>
#include "shunting-yard.h"

int main() {
    TokenMap vars;
    vars["pi"] = 3.14;
    std::cout << calculator::calculate("-pi+1", &vars) << std::endl;

    return 0;
}
```

**Comment by VinGarcia** [comment]
Hello @chrisabrams,

I made a small test here and I think I know what is going on, tell me if I am wrong:

I first ran the `make release` recipe, it compiled fine but shown some warnings (I have to look into them, they're probably from the last PR)

Then I compiled your file (I saved it as main.cpp) twice, the first one including the builtin-features the second one ignoring it here are the results:

```bash
vingarcia@vingarcia-dito:~/projects/cparse$ g++ -Wall -pedantic core-shunting-yard.o builtin-features.o main.cpp 
vingarcia@vingarcia-dito:~/projects/cparse$ ./a.out 
-2.14
vingarcia@vingarcia-dito:~/projects/cparse$ g++ -Wall -pedantic core-shunting-yard.o main.cpp 
vingarcia@vingarcia-dito:~/projects/cparse$ ./a.out 
terminate called after throwing an instance of 'syntax_error'
  what():  Invalid operator: -
Aborted (core dumped)
```

Is this what you are seeing?

**Comment by VinGarcia** [comment]
If it is, the problem is just that you are missing the builtin features, I made them like that because someone might not like the default operators and want to create something from 0.

**Comment by chrisabrams** [comment]
Yes that is the error I got! Ok, I will try to figure out how to add `builtin-features.o` to Xcode.

**Comment by chrisabrams** [comment]
Figured out Xcode, I will try to make a PR to add OS X/Xcode to the instructions.
