### ISSUE TITLE
Token names cannot have UTF8 characters

### ISSUE THREAD

**Issue by sillydan1** [cparse/cparse#75]
I have some funky token identifiers in my language. (e.g. the 'ł', '€' and 'ð' characters), but this results in syntax errors. I assume this is because token identifiers only support ASCII characters.

**Comment by sillydan1** [comment]
It looks like this functionality is determined by the `isvarchar` function in the `shunting-yard.h` file. I'll see if I can fix this myself.

**Comment by sillydan1** [comment]
This is not a perfect patch by any means, but this fixed **my** issues. I'll do a fork and pull-request with a prettier and more general patch (maybe tomorrow), so that variable names can be UTF8 characters.

```C++
static unsigned char unicodeCharCounter = 0;

...

  static inline unsigned char isvarUTF8char(const char c) {
      if(c & 0b10000000) {
          // This is the start of a unicode character!
          if(c & 0b01000000) unicodeCharCounter++;
          else return unicodeCharCounter+1;
          if(c & 0b00100000) unicodeCharCounter++;
          else return unicodeCharCounter+1;
          if(c & 0b00010000) unicodeCharCounter++;
          else return unicodeCharCounter+1;
      }
      if(unicodeCharCounter > 0) return --unicodeCharCounter;
      else return 0;
  }

  static inline std::string parseVar(const char* expr, const char** rest = 0) {
    std::stringstream ss;
    do {
        ss << *expr;
        ++expr;
    } while (isvarUTF8char(*expr) || rpnBuilder::isvarchar(*expr) || isdigit(*expr));
    if (rest) *rest = expr;
    return ss.str();
  }
```

**Comment by VinGarcia** [comment]
That's cool, thanks @sillydan1. I am looking forward to seeing your PR.

**Comment by sillydan1** [comment]
Opened the [pull request](https://github.com/cparse/cparse/pull/76) now. Closing this issue.
