### ISSUE TITLE
Project doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [cparse/cparse#77]
It should install the headers into $PREFIX/include, etc.

**Comment by VinGarcia** [comment]
It would suffice to copy the headers there? Maybe something on the Makefile like:

```makefile
install:
    cp *.h $INCPATH/include/
```

So you could use it like:

```bash
make install INCPATH=/some/path
```

**Comment by yurivict** [comment]
It should be ```cp *.h $DESTDIR$PREFIX/include/```.

**Comment by VinGarcia** [comment]
Ok, but why do we need two variables for the path?

**Comment by VinGarcia** [comment]
Also, should we add a `mkdir -p` so no errors are raised if the directory already exists or if any directory on the path also needs to be created?

**Comment by yurivict** [comment]
Yes, add ```-p```. There are no 2 variants. ```$DESTDIR$PREFIX/include/cparse/``` is the expected path.

**Comment by VinGarcia** [comment]
Ok, I need a reason for the 2 variables, I am sure you have one, but you'll have to explain to me why this is the expected path.

**Comment by yurivict** [comment]
```$DESTDIR``` is for staged builds, ```$PREFIX``` is a standard path of install prefix.

**Comment by VinGarcia** [comment]
Ok, but according to whom, is this an universal C++ pattern? Why do I need this complexity, because from what I see having 2 variables would just make the script more complicated, I need a justification for this extra complexity or I won't do it.

**Comment by yurivict** [comment]
This is a universal set of variables used in all projects based on GNU Make.

**Comment by VinGarcia** [comment]
That's cool, I will read about it and get back to you
