### ISSUE TITLE
calculator ignores variable

### ISSUE THREAD

**Issue by dimxy** [cparse/cparse#80]
I wrote a simple code example:
```
#include <iostream>
#include "shunting-yard.h"
int main() {
  TokenMap vars;
  calculator c1("v1 v2");
  std::cout << c1.eval(vars) << std::endl; // outputs "v2"
  return 0;
}
```
This prints "v2" and looks like it ignores v1 completely. I wonder why. I expected this expression would output a syntax error because of the omitted operator between v1 and v2. And this is also not two separate statements (as there is no ';' between them). What does this expression mean to the calculator?

**Comment by VinGarcia** [comment]
Hello thanks for reporting, I think this is likely to be one of the 2 problems mentioned on issue #78, namely:

```c++
        calculator calc;
        calc.compile("5x");
        printf("%f", calc.eval(tm).asDouble());
``` 

This is not throwing any errors.

I will try to fix it this weekend but it has been hard for me to save time for working on these more complicated issues. If I take forever to answer and you happen to have some time and want to try to fix this yourself I would be happy to accept a PR.

**Comment by VinGarcia** [comment]
Hello, @dimxy I've added an extra check for this type of syntax error and 2 tests to make sure this keeps working in the future.

Can you please check if it solves your problem and then close this ticket?

Thanks =]

**Comment by dimxy** [comment]
it works, perfect, thank you!
