### ISSUE TITLE
Consider adding a namespace to cparse code

### ISSUE THREAD

**Issue by dimxy** [cparse/cparse#81]
I suggest adding namespace around the cparse code.
(May be useful as I had name conflicts when I was adding cparse to my project, probably other devs might have as well)

**Comment by VinGarcia** [comment]
Hello @dimxy, yeah I know it's necessary, but I tried it a while ago the code is just too intertangled and the C++ syntax is too sensitive to changes =/.

In short, the problem that there are a few circular dependencies that are really hard to fix while migrating to a namespace. I might need to refactor the code adding some abstract classes so it's better decoupled before trying it again.

Also if you have time to try it, you are welcome to open a PR.

In any case, I am feeling good this weekend so I will try it again, but it's likely that I won't have time to finish it today and then it might be a few weeks before I can come back to it.

**Comment by VinGarcia** [comment]
Sure, that would be great =]

**Comment by VinGarcia** [comment]
Thanks @dimxy, I've merged the PR #82 it is very clean thanks! I will close this issue now.

**Comment by VinGarcia** [comment]
Actually, I feel I haven't thanked you enough, I remember how hard it was to fix this problem when I tried. Maybe you have more experience than me, in any case, thank you very much @dimxy =].

**Comment by dimxy** [comment]
I was happy to help
