### ISSUE TITLE
Program treats "." in numeric "0.x" as an operator and throw an exception!

### ISSUE THREAD

**Issue by vutrungnghiahust99** [cparse/cparse#83]
![error](https://user-images.githubusercontent.com/46959272/117157183-947a6800-ade8-11eb-8675-3f233f005388.png)
When I parse the expression: "b+0.5", the program treats "." in "0.5" as an operator, then throw an exception.

**Comment by VinGarcia** [comment]
Uhmm, this might be something new, I made an update in the code that parses numbers. I will investigate it tonight and try to fix this. Thanks for reporting.

**Comment by VinGarcia** [comment]
Actually, this was really simple to fix =], I fixed it on commit: 9576265e14fe55ef23108ec19cfea81eccb14e9d

Can you check to see if this works for you?

**Comment by vutrungnghiahust99** [comment]
It works now. Thank you so much. I have been struggling with this issue for a day at my company. By the way, could you add a README to run "test-shunting-yard.cpp", I know this file is used to run test cases but I don't know how to run it.

**Comment by VinGarcia** [comment]
Sure, I will add it to the README file, but in short the Makefile handles it, so you need to `make` installed and then you can just run:

```bash
make test
```

And everything should just work

**Comment by VinGarcia** [comment]
Done:

https://github.com/cparse/cparse/blob/master/README.md#running-the-library-tests

=]
