### ISSUE TITLE
Invalid operators, but with ALL operators

### ISSUE THREAD

**Issue by Jg747** [cparse/cparse#91]
All my expressions (on Windows) throw the "Invalid operator" exception and I can't figure out why. Here's the error:

`C:\msys64\mingw64\bin\g++.exe -fdiagnostics-color=always -g C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\Pseudo.cpp -o C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\Pseudo.exe
In file included from C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\cparse/builtin-features.inc:27,
                 from C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\Pseudo.cpp:43:
C:/Users/Jg_747/iCloudDrive/Desktop/Progetti/Pseudo/Current/cparse/builtin-features/functions.inc: In function 'cparse::packToken builtin_functions::default_type(cparse::TokenMap)':
C:/Users/Jg_747/iCloudDrive/Desktop/Progetti/Pseudo/Current/cparse/builtin-features/functions.inc:104:8: error: reference to 'INT' is ambiguous
  104 |   case INT: return "integer";
      |        ^~~
In file included from C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\Pseudo.cpp:38:
C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\cparse/shunting-yard.h:38:3: note: candidates are: 'cparse::tokType cparse::INT'
   38 |   INT = 0x22,   // == 0x20 + 0x2 => Integral numbers.
      |   ^~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:163,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:9,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/rpc.h:16,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/urlmon.h:7,
                 from C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\Pseudo.cpp:35:
C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:289:15: note:                 'typedef int INT'
  289 |   typedef int INT;
      |               ^~~
In file included from C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\cparse/builtin-features.inc:27,
                 from C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\Pseudo.cpp:43:
C:/Users/Jg_747/iCloudDrive/Desktop/Progetti/Pseudo/Current/cparse/builtin-features/functions.inc:105:8: error: reference to 'BOOL' is ambiguous
  105 |   case BOOL: return "boolean";
      |        ^~~~
In file included from C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\Pseudo.cpp:38:
C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\cparse/shunting-yard.h:39:3: note: candidates are: 'cparse::tokType cparse::BOOL'
   39 |   BOOL = 0x23,  // == 0x20 + 0x3 => Boolean Type.
      |   ^~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:9,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/rpc.h:16,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/urlmon.h:7,
                 from C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\Pseudo.cpp:35:
C:/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:131:15: note:                 'typedef int BOOL'
  131 |   typedef int BOOL;
      |               ^~~~
In file included from C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\cparse/builtin-features.inc:29,
                 from C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\Pseudo.cpp:43:
C:/Users/Jg_747/iCloudDrive/Desktop/Progetti/Pseudo/Current/cparse/builtin-features/operations.inc: In constructor 'builtin_operations::Startup::Startup()':
C:/Users/Jg_747/iCloudDrive/Desktop/Progetti/Pseudo/Current/cparse/builtin-features/operations.inc:362:28: error: reference to 'BOOL' is ambiguous
  362 |     opMap.add({UNARY, "!", BOOL}, &UnaryNotOperation);
      |                            ^~~~
In file included from C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\Pseudo.cpp:38:
C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\cparse/shunting-yard.h:39:3: note: candidates are: 'cparse::tokType cparse::BOOL'
   39 |   BOOL = 0x23,  // == 0x20 + 0x3 => Boolean Type.
      |   ^~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:9,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/rpc.h:16,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/urlmon.h:7,
                 from C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\Pseudo.cpp:35:
C:/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:131:15: note:                 'typedef int BOOL'
  131 |   typedef int BOOL;
      |               ^~~~
In file included from C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\cparse/builtin-features.inc:29,
                 from C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\Pseudo.cpp:43:
C:/Users/Jg_747/iCloudDrive/Desktop/Progetti/Pseudo/Current/cparse/builtin-features/operations.inc:362:14: error: cannot convert '<brace-enclosed initializer list>' to 'cparse::opSignature_t'
  362 |     opMap.add({UNARY, "!", BOOL}, &UnaryNotOperation);
      |     ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\Pseudo.cpp:38:
C:\Users\Jg_747\iCloudDrive\Desktop\Progetti\Pseudo\Current\cparse/shunting-yard.h:360:32: note:   initializing argument 1 of 'void cparse::opMap_t::add(cparse::opSignature_t, cparse::Operation::opFunc_t)'
  360 |   void add(const opSignature_t sig, Operation::opFunc_t func) {
      |            ~~~~~~~~~~~~~~~~~~~~^~~

La compilazione è terminata con errore/i.`

**Comment by VinGarcia** [comment]
I am assuming this issue is related to the other one, that you informed me that is already solved. So I will close this one too.

If this is not the case feel free to ask me to reopen it.
