### ISSUE TITLE
It doesn't compile in Windows and Linux, am I doing something wrong?

### ISSUE THREAD

**Issue by Jg747** [cparse/cparse#92]
For Ubuntu I followed your Linux setup guide and when I compile the code this is the error given:
https://pastebin.com/nhBt5KPX

Then I tried on VS Code but I can't compile there too,  and it give me this error:
https://pastebin.com/SUE7UgbA

The VS Code "task.json" for compiling is the following:
`{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "cppbuild",
			"label": "C/C++: g++.exe compila il file attivo",
			"command": "C:\\msys64\\mingw64\\bin\\g++.exe",
			"args": [
				"-std=c++11",
				"-fdiagnostics-color=always",
				"-g",
				"${file}",
				"-o",
				"${fileDirname}\\${fileBasenameNoExtension}.exe"
			],
			"options": {
				"cwd": "${fileDirname}"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"detail": "compilatore: C:\\msys64\\mingw64\\bin\\g++.exe"
		}
	]
}`

I don't know if I'm dumb and I'm doing something wrong but I can't figure out how to fix even if I read the issue #55 and the other one about the same problem.

Sorry for the disturb and I appreciate if you can help me

**Comment by VinGarcia** [comment]
Hey, @Jg747 I'm sorry, I missed your two issues, this happens when I don't read my emails on that day =/.

I will investigate what is going on, I imagine you have moved to use something else, but thank you for creating these issues and reporting this problem.

Regards.

**Comment by Jg747** [comment]
> Hey, @Jg747 I'm sorry, I missed your two issues, this happens when I don't read my emails on that day =/.
> 
> 
> 
> I will investigate what is going on, I imagine you have moved to use something else, but thank you for creating these issues and reporting this problem.
> 
> 
> 
> Regards.

No, don't worry, I solved the issue by myself. The error was that I wasn't compiling the .cpp files of CParse into one application, I only compiled the main and linked your library, now it works well.

**Comment by VinGarcia** [comment]
Oh that's good. I am happy it worked eventually. I will then proceed to close this issue and the other one. Feel free to create new ones if you need, I will try to respond faster next time =P
