### ISSUE TITLE
cparse/builtin-features/operators.inc

### ISSUE THREAD

**Issue by bignmllc** [cparse/cparse#96]
The precedence of operators for C++ have changed with the addition of the <=> operator in C++20.

I have updated the "operators.inc" file on my own local clone of cparse from a few days ago and updated the operator precedences to their current values and then added additional C++ operators ^, & and | for my own use.

I have attached the modified file. I have made many other customizations to my GIT clone already, so I do not want to start a new branch at this point, so I am only sending this updated file for your usage.

By the way...the README says it supports the ^  operator which it doesn't and does not mention the ** operator which cparse does support [FYI]

[operations.inc.zip](https://github.com/cparse/cparse/files/9833467/operations.inc.zip)

**Comment by bignmllc** [comment]
Dang, found a bug in my code. On line 184 in the file "operations.inc" that I uploaded, the & needs to be changed to a | ...

**Comment by bignmllc** [comment]
Here is the testing program I used that found the bug.  Please find it attached.
[test-shunting-yard.cpp.zip](https://github.com/cparse/cparse/files/9833628/test-shunting-yard.cpp.zip)

**Comment by VinGarcia** [comment]
Hello, @bignmllc I was on vacation sorry for the delay.

That is cool @bignmllc I will read it, if you could send me this in the form of a PR it would be very useful, I will consider what to do about this and get back to you in this thread soon.

**Comment by bignmllc** [comment]
Hi @VinGarcia I am not really sure how to do the PR you asked for, I think you are referring to a new Pull Request?  Even though I use Git on a base level, I am certainly not a Git expert, so I would appreciate you telling me how to do the PR. In any case, the only changes are to the "cparse/builtin-features/operators.inc" file, so is it possible just to use the file already provided?

**Comment by VinGarcia** [comment]
Yeah I can use it, I actually got 4 reports/suggestions on open-source projects during vacations so it might take some time before I stop to create it, so if you want to do it in the meantime the process is:

1. Fork the project by going up on this page and clicking on "Fork"
2. Clone your forked project, you can do this with: `git clone https://github.com/bignmllc/cparse.git some_dir_name`
3. Enter the project and the make the changes you want
4. Commit the changes and `git push origin master`
5. Enter https://github.com/bignmllc/cparse and use the interface to create a new Pull Request from bignmllc/master to cparse/master

**Comment by bignmllc** [comment]
Thanks for the instructions. I have created the PR for you as requested.

**Comment by VinGarcia** [comment]
Great, I will review it when I have the time.

Thanks!

**Comment by VinGarcia** [comment]
Oh I also just updated the README to include all the operators you mentioned, i.e. added `&`, `|` and `**`.
